#!/bin/sh

set -x

SOURCE_DIR=$1
BUILD_TYPE=Release
if [ "$#" -eq 2 ]; then
    BUILD_TYPE=$2
fi

export JOBS=4
export TLRENDER_NET=OFF
export TLRENDER_OCIO=ON
export TLRENDER_JPEG=ON
export TLRENDER_TIFF=ON
export TLRENDER_EXR=ON
export TLRENDER_SVTAV1=ON
export TLRENDER_FFMPEG=ON
export TLRENDER_FFMPEG_MINIMAL=OFF
export TLRENDER_FFMPEG_PLUGIN=ON
export TLRENDER_FFMPEG_CMD=OFF
export TLRENDER_NASM=ON
export TLRENDER_OIIO=ON
export TLRENDER_USD=OFF
export TLRENDER_BMD=OFF
export TLRENDER_BMD_SDK=
export TLRENDER_QT6=OFF
export TLRENDER_QT6_DIR=
export TLRENDER_PYTHON=OFF
export TLRENDER_PROGRAMS=ON
export TLRENDER_EXAMPLES=ON
export TLRENDER_TESTS=ON
export TLRENDER_GCOV=OFF
export FTK_API=GL_4_1
export BUILD_SHARED_LIBS=OFF

sh $SOURCE_DIR/etc/Linux/linux-build-gha.sh $SOURCE_DIR $BUILD_TYPE
