set SOURCE_DIR=%1
set BUILD_TYPE=%2
IF "%BUILD_TYPE%"=="" set BUILD_TYPE=Release

set JOBS=4
set TLRENDER_NET=OFF
set TLRENDER_OCIO=ON
set TLRENDER_JPEG=ON
set TLRENDER_TIFF=ON
set TLRENDER_EXR=ON
set TLRENDER_SVTAV1=ON
set TLRENDER_FFMPEG=ON
set TLRENDER_FFMPEG_MINIMAL=OFF
set TLRENDER_FFMPEG_PLUGIN=ON
set TLRENDER_FFMPEG_PIPE=OFF
set TLRENDER_NASM=OFF
set TLRENDER_OIIO=ON
set TLRENDER_USD=OFF
set TLRENDER_BMD=OFF
set TLRENDER_BMD_SDK=
set TLRENDER_QT6=OFF
set TLRENDER_QT6_DIR=
set TLRENDER_PYTHON=OFF
set TLRENDER_PROGRAMS=ON
set TLRENDER_EXAMPLES=ON
set TLRENDER_TESTS=ON
set TLRENDER_GCOV=OFF
set BUILD_SHARED_LIBS=OFF
set FTK_API=GL_4_1

%SOURCE_DIR%\etc\Windows\windows-build-gha.bat %SOURCE_DIR% %BUILD_TYPE%
