#!/bin/sh

set -x

BUILD_TYPE=Release
if [ "$#" -eq 1 ]; then
    BUILD_TYPE=$1
fi

export JOBS=4
export TLRENDER_NET=OFF
export TLRENDER_OCIO=ON
export TLRENDER_JPEG=ON
export TLRENDER_TIFF=ON
export TLRENDER_EXR=ON
export TLRENDER_FFMPEG=ON
export TLRENDER_FFMPEG_MINIMAL=OFF
export TLRENDER_NASM=ON
export TLRENDER_OIIO=ON
export TLRENDER_USD=OFF
export TLRENDER_BMD=OFF
export TLRENDER_BMD_SDK=
export TLRENDER_QT6=OFF
export TLRENDER_QT6_DIR=
export TLRENDER_QT5=OFF
export TLRENDER_QT5_DIR=
export TLRENDER_PYTHON=OFF
export TLRENDER_PROGRAMS=ON
export TLRENDER_EXAMPLES=ON
export TLRENDER_TESTS=ON
export TLRENDER_GCOV=OFF
export FTK_API=GL_4_1
export BUILD_SHARED_LIBS=OFF

sh tlRender/etc/Linux/linux-build-gha.sh $BUILD_TYPE
